spring:
  application:
      name: finleap-weather
  datasource:
    url: jdbc:h2:mem:finleap;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    platform: h2
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        show_sql: false
        use_sql_comments: true
        format_sql: true
  h2:
    console:
      enabled: true
      path: /console
      settings:
        trace: false
        web-allow-others: false
  main:
      allow-bean-definition-overriding: true


feign:
  hystrix:
    enabled: true
  client:
    config:
      feignName:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: full
        requestInterceptors:
          - com.finleap.weather.config.ForecastRequestInterceptor
        decode404: true
        
hystrix:
  command:
    default:
      execution:
        isolation:
          strategy: SEMAPHORE

openweather:
        client:
            name: open-weather
            url: api.openweathermap.org
            appid: fbdaa375ca8c18780b2e5e12d9f6de2a